sources:
  - name: raw
    description: Raw data from CSV files
    database: postgres
    schema:   raw

    tables:
      - name: table_g01_nsw_lga
      - name: table_g02_nsw_lga
      - name: table_listings
      - name: table_nsw_lga_code
      - name: table_nsw_lga_suburb
   